/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per bMS release and tool: the query parameters of the tool's GET operation,
 * as the properties the tool offers (#179). Tools send exactly these, except
 * the client-side countOnly (#165), which the core handles.
 */
import { type QueryParameterTable, COUNT_ONLY_PROPERTY, PAGE_PROPERTY, PAGE_SIZE_PROPERTY } from "@bconnect/mcp-core";

export const QUERY_PARAMETERS: QueryParameterTable = {
  "25R2": {
    list_os_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_os_folders_by_folder: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_os_windows_endpoints: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are EndpointId or EndpointName."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are EndpointName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
  },
  "26R1": {
    list_os_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_os_folders_by_folder: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_os_windows_endpoints: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are EndpointId or EndpointName."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are EndpointName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
  },
};
