/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_os_folders: ["GET"],
  get_os_folder: ["GET"],
  list_os_folders_by_folder: ["GET"],
  list_os_windows_endpoints: ["GET"],
  get_os_windows_endpoint: ["GET"],
  create_os_folder: ["POST"],
  update_os_folder: ["PATCH"],
  delete_os_folder: ["DELETE"],
  update_os_windows_endpoint: ["PATCH"],
};
