/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_os_folders: ["25R2", "26R1"],
  get_os_folder: ["25R2", "26R1"],
  list_os_folders_by_folder: ["25R2", "26R1"],
  list_os_windows_endpoints: ["25R2", "26R1"],
  get_os_windows_endpoint: ["25R2", "26R1"],
  create_os_folder: ["25R2", "26R1"],
  update_os_folder: ["25R2", "26R1"],
  delete_os_folder: ["25R2", "26R1"],
  update_os_windows_endpoint: ["25R2", "26R1"],
};
