/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per bMS release and tool: the query parameters of the tool's GET operation,
 * as the properties the tool offers (#179). Tools send exactly these.
 */
import { type QueryParameterTable, PAGE_PROPERTY, PAGE_SIZE_PROPERTY } from "@bconnect/mcp-core";

export const QUERY_PARAMETERS: QueryParameterTable = {
  "25R2": {
    list_security_groups: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Only Name is supported (e. g. Name asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters results by exactly matching name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_security_profiles: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Only Name is supported (e. g. Name asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters results by exactly matching name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
  },
  "26R1": {
    list_security_groups: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Only Name is supported (e. g. Name asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters results by exactly matching name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_security_profiles: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Only Name is supported (e. g. Name asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters results by exactly matching name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_download_jobs: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Name or LastExecution (e. g. Name asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and LocalPathName."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      StateValue: {"type":"string","enum":["Unknown","Running","Success","Error","RescheduledSuccess","RescheduledError"],"description":"Filters result by matching StateValue."},
      LastExecution: {"type":"string","description":"Filters on lastExecution. Date values have to be specified in ISO 8601 format. They can be filtered by adding the prefix 'lt' or 'gt' (e.g. gt 2023-07-28T08:01:03.375Z)."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
  },
};
