/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  get_management_server: ["25R2", "26R1"],
  get_gateway: ["25R2", "26R1"],
  get_dip_status: ["25R2", "26R1"],
  get_vpn_appliance: ["25R2", "26R1"],
  list_microservices: ["25R2", "26R1"],
  get_microservice: ["25R2", "26R1"],
  start_microservice: ["25R2", "26R1"],
  stop_microservice: ["25R2", "26R1"],
  restart_microservice: ["25R2", "26R1"],
  list_cloud_connectors: ["25R2", "26R1"],
  list_pxe_relays: ["25R2", "26R1"],
  list_security_groups: ["25R2", "26R1"],
  get_security_group: ["25R2", "26R1"],
  create_security_group: ["25R2", "26R1"],
  update_security_group: ["25R2", "26R1"],
  delete_security_group: ["25R2", "26R1"],
  list_security_profiles: ["25R2", "26R1"],
  get_security_profile: ["25R2", "26R1"],
  create_security_profile: ["25R2", "26R1"],
  update_security_profile: ["25R2", "26R1"],
  delete_security_profile: ["25R2", "26R1"],
  get_access_rights: ["25R2", "26R1"],
  update_object_permission: ["25R2", "26R1"],
  restart_management_server: ["25R2", "26R1"],
  cancel_scheduled_restart: ["25R2", "26R1"],
  list_api_keys: ["26R1"],
  simulate_msw_cleanup: ["26R1"],
  msw_cleanup: ["26R1"],
  list_download_jobs: ["26R1"],
  get_download_job: ["26R1"],
};
