/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  get_management_server: ["GET"],
  get_gateway: ["GET"],
  get_dip_status: ["GET"],
  get_vpn_appliance: ["GET"],
  list_microservices: ["GET"],
  get_microservice: ["GET"],
  start_microservice: ["POST"],
  stop_microservice: ["POST"],
  restart_microservice: ["POST"],
  list_cloud_connectors: ["GET"],
  list_pxe_relays: ["GET"],
  list_security_groups: ["GET"],
  get_security_group: ["GET"],
  create_security_group: ["POST"],
  update_security_group: ["PATCH"],
  delete_security_group: ["DELETE"],
  list_security_profiles: ["GET"],
  get_security_profile: ["GET"],
  create_security_profile: ["POST"],
  update_security_profile: ["PATCH"],
  delete_security_profile: ["DELETE"],
  get_access_rights: ["GET"],
  update_object_permission: ["PATCH"],
  restart_management_server: ["POST"],
  cancel_scheduled_restart: ["POST"],
  list_api_keys: ["GET"],
  simulate_msw_cleanup: ["POST"],
  msw_cleanup: ["POST"],
  list_download_jobs: ["GET"],
  get_download_job: ["GET"],
};
