/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_endpoints_by_logical_group: ["GET"],
  list_android_endpoints_by_logical_group: ["GET"],
  list_ios_endpoints_by_logical_group: ["GET"],
  list_linux_endpoints_by_logical_group: ["GET"],
  list_mac_endpoints_by_logical_group: ["GET"],
  list_network_endpoints_by_logical_group: ["GET"],
  list_windows_endpoints_by_logical_group: ["GET"],
  list_industrial_endpoints_by_logical_group: ["GET"],
  list_logical_groups_by_logical_group: ["GET"],
  list_endpoints_by_static_group: ["GET"],
  list_android_endpoints_by_static_group: ["GET"],
  list_ios_endpoints_by_static_group: ["GET"],
  list_linux_endpoints_by_static_group: ["GET"],
  list_mac_endpoints_by_static_group: ["GET"],
  list_network_endpoints_by_static_group: ["GET"],
  list_windows_endpoints_by_static_group: ["GET"],
  list_industrial_endpoints_by_static_group: ["GET"],
  list_endpoints_by_dynamic_group: ["GET"],
  list_windows_endpoints_by_dynamic_group: ["GET"],
  list_endpoints_by_universal_dynamic_group: ["GET"],
  list_android_endpoints_by_universal_dynamic_group: ["GET"],
  list_ios_endpoints_by_universal_dynamic_group: ["GET"],
  list_linux_endpoints_by_universal_dynamic_group: ["GET"],
  list_mac_endpoints_by_universal_dynamic_group: ["GET"],
  list_network_endpoints_by_universal_dynamic_group: ["GET"],
  list_windows_endpoints_by_universal_dynamic_group: ["GET"],
  list_industrial_endpoints_by_universal_dynamic_group: ["GET"],
  list_endpoints_by_ad_user: ["GET"],
  list_android_endpoints_by_ad_user: ["GET"],
  list_ios_endpoints_by_ad_user: ["GET"],
  list_linux_endpoints_by_ad_user: ["GET"],
  list_mac_endpoints_by_ad_user: ["GET"],
  list_windows_endpoints_by_ad_user: ["GET"],
};
