/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_group_members: ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=WindowsEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=MacEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=LinuxEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=AndroidEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=IOSEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=NetworkEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=LogicalGroup,memberType=IndustrialEndpoint]": ["25R2"],
  "list_group_members[groupKind=LogicalGroup,memberType=LogicalGroup]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=WindowsEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=MacEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=LinuxEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=AndroidEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=IOSEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=NetworkEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=StaticGroup,memberType=IndustrialEndpoint]": ["25R2"],
  "list_group_members[groupKind=DynamicGroup,memberType=]": ["25R2", "26R1"],
  "list_group_members[groupKind=DynamicGroup,memberType=WindowsEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=WindowsEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=MacEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=LinuxEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=AndroidEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=IOSEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=NetworkEndpoint]": ["25R2", "26R1"],
  "list_group_members[groupKind=UniversalDynamicGroup,memberType=IndustrialEndpoint]": ["25R2"],
  list_ad_user_endpoints: ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=]": ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=WindowsEndpoint]": ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=MacEndpoint]": ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=LinuxEndpoint]": ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=AndroidEndpoint]": ["25R2", "26R1"],
  "list_ad_user_endpoints[endpointType=IOSEndpoint]": ["25R2", "26R1"],
};
