/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_endpoints_by_logical_group: ["25R2", "26R1"],
  list_android_endpoints_by_logical_group: ["25R2", "26R1"],
  list_ios_endpoints_by_logical_group: ["25R2", "26R1"],
  list_linux_endpoints_by_logical_group: ["25R2", "26R1"],
  list_mac_endpoints_by_logical_group: ["25R2", "26R1"],
  list_network_endpoints_by_logical_group: ["25R2", "26R1"],
  list_windows_endpoints_by_logical_group: ["25R2", "26R1"],
  list_industrial_endpoints_by_logical_group: ["25R2"],
  list_logical_groups_by_logical_group: ["25R2", "26R1"],
  list_endpoints_by_static_group: ["25R2", "26R1"],
  list_android_endpoints_by_static_group: ["25R2", "26R1"],
  list_ios_endpoints_by_static_group: ["25R2", "26R1"],
  list_linux_endpoints_by_static_group: ["25R2", "26R1"],
  list_mac_endpoints_by_static_group: ["25R2", "26R1"],
  list_network_endpoints_by_static_group: ["25R2", "26R1"],
  list_windows_endpoints_by_static_group: ["25R2", "26R1"],
  list_industrial_endpoints_by_static_group: ["25R2"],
  list_endpoints_by_dynamic_group: ["25R2", "26R1"],
  list_windows_endpoints_by_dynamic_group: ["25R2", "26R1"],
  list_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_android_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_ios_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_linux_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_mac_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_network_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_windows_endpoints_by_universal_dynamic_group: ["25R2", "26R1"],
  list_industrial_endpoints_by_universal_dynamic_group: ["25R2"],
  list_endpoints_by_ad_user: ["25R2", "26R1"],
  list_android_endpoints_by_ad_user: ["25R2", "26R1"],
  list_ios_endpoints_by_ad_user: ["25R2", "26R1"],
  list_linux_endpoints_by_ad_user: ["25R2", "26R1"],
  list_mac_endpoints_by_ad_user: ["25R2", "26R1"],
  list_windows_endpoints_by_ad_user: ["25R2", "26R1"],
};
