/**
 * GENERATED by scripts/generate-query-parameters.mjs from src/operations.ts —
 * do not edit. Regenerate after an operations.ts change;
 * __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per merged tool (REQ-SRV-029, #174): its routes (variants) and the selector
 * values that choose each; null means the argument is left out.
 */
import type { ToolVariantTable } from "@bconnect/mcp-core";

export const TOOL_VARIANTS: ToolVariantTable = {
  list_group_members: {
    "list_group_members[groupKind=LogicalGroup,memberType=]": {"groupKind": "LogicalGroup", "memberType": null},
    "list_group_members[groupKind=LogicalGroup,memberType=WindowsEndpoint]": {"groupKind": "LogicalGroup", "memberType": "WindowsEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=MacEndpoint]": {"groupKind": "LogicalGroup", "memberType": "MacEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=LinuxEndpoint]": {"groupKind": "LogicalGroup", "memberType": "LinuxEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=AndroidEndpoint]": {"groupKind": "LogicalGroup", "memberType": "AndroidEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=IOSEndpoint]": {"groupKind": "LogicalGroup", "memberType": "IOSEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=NetworkEndpoint]": {"groupKind": "LogicalGroup", "memberType": "NetworkEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=IndustrialEndpoint]": {"groupKind": "LogicalGroup", "memberType": "IndustrialEndpoint"},
    "list_group_members[groupKind=LogicalGroup,memberType=LogicalGroup]": {"groupKind": "LogicalGroup", "memberType": "LogicalGroup"},
    "list_group_members[groupKind=StaticGroup,memberType=]": {"groupKind": "StaticGroup", "memberType": null},
    "list_group_members[groupKind=StaticGroup,memberType=WindowsEndpoint]": {"groupKind": "StaticGroup", "memberType": "WindowsEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=MacEndpoint]": {"groupKind": "StaticGroup", "memberType": "MacEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=LinuxEndpoint]": {"groupKind": "StaticGroup", "memberType": "LinuxEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=AndroidEndpoint]": {"groupKind": "StaticGroup", "memberType": "AndroidEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=IOSEndpoint]": {"groupKind": "StaticGroup", "memberType": "IOSEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=NetworkEndpoint]": {"groupKind": "StaticGroup", "memberType": "NetworkEndpoint"},
    "list_group_members[groupKind=StaticGroup,memberType=IndustrialEndpoint]": {"groupKind": "StaticGroup", "memberType": "IndustrialEndpoint"},
    "list_group_members[groupKind=DynamicGroup,memberType=]": {"groupKind": "DynamicGroup", "memberType": null},
    "list_group_members[groupKind=DynamicGroup,memberType=WindowsEndpoint]": {"groupKind": "DynamicGroup", "memberType": "WindowsEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=]": {"groupKind": "UniversalDynamicGroup", "memberType": null},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=WindowsEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "WindowsEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=MacEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "MacEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=LinuxEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "LinuxEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=AndroidEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "AndroidEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=IOSEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "IOSEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=NetworkEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "NetworkEndpoint"},
    "list_group_members[groupKind=UniversalDynamicGroup,memberType=IndustrialEndpoint]": {"groupKind": "UniversalDynamicGroup", "memberType": "IndustrialEndpoint"},
  },
  list_ad_user_endpoints: {
    "list_ad_user_endpoints[endpointType=]": {"endpointType": null},
    "list_ad_user_endpoints[endpointType=WindowsEndpoint]": {"endpointType": "WindowsEndpoint"},
    "list_ad_user_endpoints[endpointType=MacEndpoint]": {"endpointType": "MacEndpoint"},
    "list_ad_user_endpoints[endpointType=LinuxEndpoint]": {"endpointType": "LinuxEndpoint"},
    "list_ad_user_endpoints[endpointType=AndroidEndpoint]": {"endpointType": "AndroidEndpoint"},
    "list_ad_user_endpoints[endpointType=IOSEndpoint]": {"endpointType": "IOSEndpoint"},
  },
};
