/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_job_definitions: ["25R2", "26R1"],
  get_job_definition: ["25R2", "26R1"],
  list_job_instances: ["25R2", "26R1"],
  get_job_instance: ["25R2", "26R1"],
  list_endpoint_job_instances: ["25R2", "26R1"],
  list_job_instances_by_definition: ["25R2", "26R1"],
  list_job_instances_by_logical_group: ["25R2", "26R1"],
  list_job_definitions_by_folder: ["25R2", "26R1"],
  create_job_instance: ["25R2", "26R1"],
  start_job_instance: ["25R2", "26R1"],
  stop_job_instance: ["25R2", "26R1"],
  resume_job_instance: ["25R2", "26R1"],
  delete_job_instance: ["25R2", "26R1"],
  create_job_folder: ["25R2", "26R1"],
  update_job_folder: ["25R2", "26R1"],
  delete_job_folder: ["25R2", "26R1"],
  assign_job_to_logical_group: ["25R2", "26R1"],
  assign_job_to_static_group: ["25R2", "26R1"],
  assign_job_to_dynamic_group: ["25R2", "26R1"],
  assign_job_to_universal_dynamic_group: ["25R2", "26R1"],
  create_kiosk_release: ["25R2", "26R1"],
  withdraw_kiosk_release: ["25R2", "26R1"],
  list_kiosk_releases: ["25R2", "26R1"],
  get_kiosk_release: ["25R2", "26R1"],
  list_job_folders: ["25R2", "26R1"],
  get_job_folder: ["25R2", "26R1"],
  list_job_subfolders: ["25R2", "26R1"],
  list_kiosk_releases_by_job_definition: ["25R2", "26R1"],
  list_kiosk_releases_by_endpoint: ["25R2", "26R1"],
  list_kiosk_releases_by_ad_object: ["25R2", "26R1"],
  list_kiosk_releases_by_logical_group: ["25R2", "26R1"],
  list_job_instances_by_static_group: ["25R2", "26R1"],
  list_job_instances_by_dynamic_group: ["25R2", "26R1"],
  list_job_instances_by_universal_dynamic_group: ["25R2", "26R1"],
};
