/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_job_definitions: ["GET"],
  get_job_definition: ["GET"],
  list_job_instances: ["GET"],
  get_job_instance: ["GET"],
  list_endpoint_job_instances: ["GET"],
  list_job_instances_by_definition: ["GET"],
  list_job_instances_by_logical_group: ["GET"],
  list_job_definitions_by_folder: ["GET"],
  create_job_instance: ["POST"],
  start_job_instance: ["POST"],
  stop_job_instance: ["POST"],
  resume_job_instance: ["POST"],
  delete_job_instance: ["DELETE"],
  create_job_folder: ["POST"],
  update_job_folder: ["PATCH"],
  delete_job_folder: ["DELETE"],
  assign_job_to_logical_group: ["POST"],
  assign_job_to_static_group: ["POST"],
  assign_job_to_dynamic_group: ["POST"],
  assign_job_to_universal_dynamic_group: ["POST"],
  create_kiosk_release: ["POST"],
  withdraw_kiosk_release: ["DELETE"],
  list_kiosk_releases: ["GET"],
  get_kiosk_release: ["GET"],
  list_job_folders: ["GET"],
  get_job_folder: ["GET"],
  list_job_subfolders: ["GET"],
  list_kiosk_releases_by_job_definition: ["GET"],
  list_kiosk_releases_by_endpoint: ["GET"],
  list_kiosk_releases_by_ad_object: ["GET"],
  list_kiosk_releases_by_logical_group: ["GET"],
  list_job_instances_by_static_group: ["GET"],
  list_job_instances_by_dynamic_group: ["GET"],
  list_job_instances_by_universal_dynamic_group: ["GET"],
};
