/**
 * The two generated artifacts must match the 26R1 spec they claim to come from.
 *
 * `CONTRIBUTING.md:33-34` already admits the root cause this guards: there was
 * no codegen script, so `src/generated/*` was regenerated by hand, occasionally,
 * and drifted. The visible consequence in this package was a hand-written
 * `type EntraId26R1 = { EntraIdDeviceId?: string }` intersected onto the Windows
 * query types because the checked-in types were emitted from 25R2 while the
 * tools advertised a 26R1 parameter.
 *
 * Both artifacts now have a generator (`npm run generate`) and this test is the
 * ratchet: regenerate the file fresh from openapi-specs/26R1 and compare. It
 * fails the moment the spec moves and the checked-in file does not.
 *
 * The runtime index matters more than the types here, because it is what
 * `defineTools()` reads to build the advertised schemas and the validation
 * rules — a stale index is a catalogue that describes a bMS nobody is running.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

 
// @ts-expect-error — plain ESM, no types; it is a build script, not a module.
import { renderOperationIndexModule, OUTPUT_PATH, SPEC_PATH } from '../../scripts/generate-operation-index.mjs';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('src/generated/endpoints-operation-index.ts', () => {
  it('is byte-identical to a fresh run against openapi-specs/26R1', () => {
    const fresh = (renderOperationIndexModule as () => string)();
    const checkedIn = readFileSync(OUTPUT_PATH as string, 'utf8');
    expect(
      checkedIn,
      'src/generated/endpoints-operation-index.ts is stale — run `npm run generate`'
    ).toBe(fresh);
  });

  it('is built from the 26R1 spec, not 25R2', () => {
    expect(SPEC_PATH as string).toContain('26R1');
  });
});

describe('src/generated/endpoints-types.ts', () => {
  // Byte-identity for the TYPES is asserted suite-wide, in
  // __tests__/generated-types-are-fresh.test.ts, against the one generator that
  // renders all twenty-two type files (`npm run generate` at the repo root).
  // Duplicating it here would mean two generators disagreeing about flags is a
  // failure in this package rather than in the one that owns them. What is
  // asserted here is what is specific to this package: the two facts the
  // regeneration was FOR.

  it('keeps Deprecated_IndustrialEndpoint in the EndpointType enum', () => {
    // Product decision 3, and the vendor's own instruction in the spec:
    // "Removed in 26.1. Keep to avoid gaps in enum values." The ROUTES are gone
    // (see removed-tools.ts); the enum VALUE stays, because historical endpoint
    // records still carry it and dropping it would break their deserialisation.
    const types = readFileSync(join(packageRoot, 'src/generated/endpoints-types.ts'), 'utf8');
    expect(types).toContain('"Deprecated_IndustrialEndpoint"');
    expect(types).toContain('Keep to avoid gaps in enum values');
  });

  it('no longer needs the hand-written EntraIdDeviceId intersection', () => {
    // 25R2 does not declare EntraIdDeviceId; 26R1 does, on both Windows list
    // routes. The `EntraId26R1` workaround in modules/endpoints.ts existed only
    // to paper over that, and its removal is only safe because of this.
    const types = readFileSync(join(packageRoot, 'src/generated/endpoints-types.ts'), 'utf8');
    expect(types).toContain('EntraIdDeviceId');

    const module = readFileSync(join(packageRoot, 'src/modules/endpoints.ts'), 'utf8');
    expect(module).not.toContain('EntraId26R1');
  });
});
