/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per bMS release and tool: the query parameters of the tool's GET operation,
 * as the properties the tool offers (#179). Tools send exactly these, except
 * the client-side countOnly (#165), which the core handles.
 */
import { type QueryParameterTable, COUNT_ONLY_PROPERTY, PAGE_PROPERTY, PAGE_SIZE_PROPERTY } from "@bconnect/mcp-core";

export const QUERY_PARAMETERS: QueryParameterTable = {
  "25R2": {

  },
  "26R1": {
    list_detected_rule_violations: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are EndpointName or RuleName (e.g. RuleName asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are EndpointName or RuleName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_detected_rule_violations_for_endpoint: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are EndpointName or RuleName (e.g. RuleName asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are EndpointName or RuleName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_detected_vulnerabilities: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are EndpointName or CveId (e.g. EndpointName asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are EndpointName or CveId."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_detected_vulnerabilities_for_endpoint: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is CveId (e.g. CveId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is CveId."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_mobile_device_rules: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are RuleName or Description (e.g. RuleName asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are RuleName or Description."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
    list_vulnerabilities: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are CveId or CvssScore (e.g. CveId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are CveId, AffectedProducts or AffectedOperatingSystems."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      countOnly: COUNT_ONLY_PROPERTY,
    },
  },
};
