/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_detected_rule_violations: ["GET"],
  list_detected_rule_violations_for_endpoint: ["GET"],
  list_detected_vulnerabilities: ["GET"],
  list_detected_vulnerabilities_for_endpoint: ["GET"],
  list_mobile_device_rules: ["GET"],
  get_mobile_device_rule: ["GET"],
  list_vulnerabilities: ["GET"],
  get_vulnerability: ["GET"],
};
