/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_detected_rule_violations: ["26R1"],
  list_detected_rule_violations_for_endpoint: ["26R1"],
  list_detected_vulnerabilities: ["26R1"],
  list_detected_vulnerabilities_for_endpoint: ["26R1"],
  list_mobile_device_rules: ["26R1"],
  get_mobile_device_rule: ["26R1"],
  list_vulnerabilities: ["26R1"],
  get_vulnerability: ["26R1"],
};
