/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_variable_definitions: ["GET"],
  get_variable_definition: ["GET"],
  create_variable_definition: ["POST"],
  update_variable_definition: ["PATCH"],
  delete_variable_definition: ["DELETE"],
  list_variable_instances: ["GET"],
  get_variable_instance: ["GET"],
  list_variable_instances_by_endpoint: ["GET"],
  list_variable_instances_by_logical_group: ["GET"],
  list_variable_instances_by_ad_object: ["GET"],
  list_variable_instances_by_job_definition: ["GET"],
  list_variable_instances_by_application: ["GET"],
  update_variable_instance: ["PATCH"],
};
