/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_variable_definitions: ["25R2", "26R1"],
  get_variable_definition: ["25R2", "26R1"],
  create_variable_definition: ["25R2", "26R1"],
  update_variable_definition: ["25R2", "26R1"],
  delete_variable_definition: ["25R2", "26R1"],
  list_variable_instances: ["25R2", "26R1"],
  get_variable_instance: ["25R2", "26R1"],
  list_variable_instances_by_endpoint: ["25R2", "26R1"],
  list_variable_instances_by_logical_group: ["25R2", "26R1"],
  list_variable_instances_by_ad_object: ["25R2", "26R1"],
  list_variable_instances_by_job_definition: ["25R2", "26R1"],
  list_variable_instances_by_application: ["25R2", "26R1"],
  update_variable_instance: ["25R2", "26R1"],
};
