/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_bitlocker_windows_endpoints: ["GET"],
  get_bitlocker_windows_endpoint: ["GET"],
  get_local_admin_accounts: ["GET"],
  patch_local_admin_user_credentials: ["PATCH"],
  refresh_local_admin_account_expiry: ["POST"],
  list_defender_threats: ["GET"],
  get_defender_threat: ["GET"],
  list_defender_threats_by_endpoint: ["GET"],
  list_defender_threats_by_logical_group: ["GET"],
  list_defender_windows_endpoints: ["GET"],
  get_defender_windows_endpoint: ["GET"],
  get_bitlocker_secrets: ["GET"],
  update_bitlocker_pin: ["PATCH"],
};
