/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_bitlocker_windows_endpoints: ["25R2", "26R1"],
  get_bitlocker_windows_endpoint: ["25R2", "26R1"],
  get_local_admin_accounts: ["25R2", "26R1"],
  patch_local_admin_user_credentials: ["25R2", "26R1"],
  refresh_local_admin_account_expiry: ["25R2", "26R1"],
  list_defender_threats: ["25R2", "26R1"],
  get_defender_threat: ["25R2", "26R1"],
  list_defender_threats_by_endpoint: ["25R2", "26R1"],
  list_defender_threats_by_logical_group: ["25R2", "26R1"],
  list_defender_windows_endpoints: ["25R2", "26R1"],
  get_defender_windows_endpoint: ["25R2", "26R1"],
  get_bitlocker_secrets: ["26R1"],
  update_bitlocker_pin: ["26R1"],
};
