/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per bMS release and tool: the query parameters of the tool's GET operation,
 * as the properties the tool offers (#179). Tools send exactly these.
 */
import { type QueryParameterTable, PAGE_PROPERTY, PAGE_SIZE_PROPERTY } from "@bconnect/mcp-core";

export const QUERY_PARAMETERS: QueryParameterTable = {
  "25R2": {
    list_assets: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_in_asset_stock: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_logical_group: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_windows_endpoint: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_stock_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_stock_subfolders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
    },
    list_asset_type_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_type_subfolders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
    },
    list_asset_types: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Name, Comments, Contact, InventoryNumber, Url, CostCenter, GuidParent"},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, Comments, Contact, InventoryNumber, Url, CostCenter, GuidParent."},
      ShowSummary: {"type":"boolean","description":"Compute summary data"},
      Icon: {"type":"boolean","description":"Include encoded icon data"},
      AdditionalProperties: {"type":"boolean","description":"Include additional properties of asset types"},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
  },
  "26R1": {
    list_assets: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_in_asset_stock: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_logical_group: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_windows_endpoint: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_stock_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_stock_subfolders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
    },
    list_asset_type_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_asset_type_subfolders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
    },
    list_asset_types: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Name, Comments, Contact, InventoryNumber, Url, CostCenter, GuidParent"},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, Comments, Contact, InventoryNumber, Url, CostCenter, GuidParent."},
      ShowSummary: {"type":"boolean","description":"Compute summary data"},
      Icon: {"type":"boolean","description":"Include encoded icon data"},
      AdditionalProperties: {"type":"boolean","description":"Include additional properties of asset types"},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_org_unit: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_assets_by_ad_object: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are AssetId, OwnerId, OwnerType, etc (e.g. OwnerId asc)."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, InventoryNumber, Contact and CostCenter."},
      DisplayName: {"type":"string","description":"Filters result by matching the exact value against DisplayName."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
  },
};
