/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_assets: ["GET"],
  create_asset: ["POST"],
  get_asset: ["GET"],
  update_asset: ["PATCH"],
  delete_asset: ["DELETE"],
  list_assets_in_asset_stock: ["GET"],
  list_assets_by_logical_group: ["GET"],
  list_assets_by_windows_endpoint: ["GET"],
  list_asset_stock_folders: ["GET"],
  create_asset_stock_folder: ["POST"],
  get_asset_stock_folder: ["GET"],
  update_asset_stock_folder: ["PATCH"],
  delete_asset_stock_folder: ["DELETE"],
  list_asset_stock_subfolders: ["GET"],
  list_asset_type_folders: ["GET"],
  create_asset_type_folder: ["POST"],
  get_asset_type_folder: ["GET"],
  update_asset_type_folder: ["PATCH"],
  delete_asset_type_folder: ["DELETE"],
  list_asset_type_subfolders: ["GET"],
  list_asset_types: ["GET"],
  create_asset_type: ["POST"],
  get_asset_type: ["GET"],
  delete_asset_type: ["DELETE"],
  list_assets_by_org_unit: ["GET"],
  list_assets_by_ad_object: ["GET"],
};
