/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_assets: ["25R2", "26R1"],
  create_asset: ["25R2", "26R1"],
  get_asset: ["25R2", "26R1"],
  update_asset: ["25R2", "26R1"],
  delete_asset: ["25R2", "26R1"],
  list_assets_in_asset_stock: ["25R2", "26R1"],
  list_assets_by_logical_group: ["25R2", "26R1"],
  list_assets_by_windows_endpoint: ["25R2", "26R1"],
  list_asset_stock_folders: ["25R2", "26R1"],
  create_asset_stock_folder: ["25R2", "26R1"],
  get_asset_stock_folder: ["25R2", "26R1"],
  update_asset_stock_folder: ["25R2", "26R1"],
  delete_asset_stock_folder: ["25R2", "26R1"],
  list_asset_stock_subfolders: ["25R2", "26R1"],
  list_asset_type_folders: ["25R2", "26R1"],
  create_asset_type_folder: ["25R2", "26R1"],
  get_asset_type_folder: ["25R2", "26R1"],
  update_asset_type_folder: ["25R2", "26R1"],
  delete_asset_type_folder: ["25R2", "26R1"],
  list_asset_type_subfolders: ["25R2", "26R1"],
  list_asset_types: ["25R2", "26R1"],
  create_asset_type: ["25R2", "26R1"],
  get_asset_type: ["25R2", "26R1"],
  delete_asset_type: ["25R2", "26R1"],
  list_assets_by_org_unit: ["26R1"],
  list_assets_by_ad_object: ["26R1"],
};
