/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_universal_dynamic_groups: ["GET"],
  get_universal_dynamic_group: ["GET"],
  list_universal_dynamic_groups_by_folder: ["GET"],
  list_udg_folders: ["GET"],
  get_udg_folder: ["GET"],
  list_udg_folders_by_folder: ["GET"],
};
