/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_universal_dynamic_groups: ["26R1"],
  get_universal_dynamic_group: ["26R1"],
  list_universal_dynamic_groups_by_folder: ["26R1"],
  list_udg_folders: ["26R1"],
  get_udg_folder: ["26R1"],
  list_udg_folders_by_folder: ["26R1"],
};
