/**
 * The bConnect API operation each tool of this server calls, by operationId in
 * the `endpoints` OpenAPI spec (openapi-specs/<release>/). One line per tool; add
 * one when you add a tool.
 *
 * The spec-conformance guard (__tests__/spec-conformance.guard.test.ts) checks
 * every tool against its entry for both bMS releases: the operation must exist,
 * and the tool's request must go to that operation's method and route.
 */
export const TOOL_OPERATIONS: Readonly<Record<string, readonly string[]>> = {
  list_endpoints: ['GetEndpoints'],
  get_endpoint: ['GetEndpoint'],
  search_endpoints: ['GetEndpoints'],
  list_windows_endpoints: ['GetWindowsEndpoints'],
  get_windows_endpoint: ['GetWindowsEndpoint'],
  list_logical_groups: ['GetLogicalGroups'],
  get_logical_group: ['GetLogicalGroup'],
  list_group_endpoints: ['GetEndpointsByLogicalGroupId'],
  list_linux_endpoints: ['GetLinuxEndpoints'],
  list_mac_endpoints: ['GetMacEndpoints'],
  get_linux_endpoint: ['GetLinuxEndpoint'],
  get_mac_endpoint: ['GetMacEndpoint'],
  list_endpoints_by_logical_group: ['GetEndpointsByLogicalGroupId'],
  list_windows_endpoints_by_logical_group: ['GetWindowsEndpointsByLogicalGroupId'],
  list_android_endpoints: ['GetAndroidEndpoints'],
  get_android_endpoint: ['GetAndroidEndpoint'],
  list_ios_endpoints: ['GetIOSEndpoints'],
  get_ios_endpoint: ['GetIOSEndpoint'],
  start_android_enrollment: ['StartAndroidEndpointEnrollment'],
  start_ios_enrollment: ['StartIosEndpointEnrollment'],
  create_android_endpoint: ['CreateAndroidEndpoint'],
  update_android_endpoint: ['UpdateAndroidEndpoint'],
  delete_android_endpoint: ['DeleteAndroidEndpoint'],
  create_ios_endpoint: ['CreateIOSEndpoint'],
  update_ios_endpoint: ['UpdateIOSEndpoint'],
  delete_ios_endpoint: ['DeleteIOSEndpoint'],
  create_windows_endpoint: ['CreateWindowsEndpoint'],
  update_windows_endpoint: ['UpdateWindowsEndpoint'],
  delete_windows_endpoint: ['DeleteWindowsEndpoint'],
  start_windows_enrollment: ['StartWindowsEndpointEnrollment'],
  trigger_intune_installation: ['TriggerInstallationViaIntune'],
  create_linux_endpoint: ['CreateLinuxEndpoint'],
  update_linux_endpoint: ['UpdateLinuxEndpoint'],
  delete_linux_endpoint: ['DeleteLinuxEndpoint'],
  create_mac_endpoint: ['CreateMacEndpoint'],
  update_mac_endpoint: ['UpdateMacEndpoint'],
  delete_mac_endpoint: ['DeleteMacEndpoint'],
  start_mac_enrollment: ['StartMacEndpointEnrollment'],
  create_logical_group: ['CreateLogicalGroup'],
  update_logical_group: ['UpdateLogicalGroup'],
  delete_logical_group: ['DeleteLogicalGroup'],
  get_maintenance_window_for_endpoint: ['GetMaintenanceWindowForEndpointById'],
  create_maintenance_window_for_endpoint: ['CreateMaintenanceWindowForEndpointById'],
  update_maintenance_window_for_endpoint: ['UpdateMaintenanceWindowForEndpointById'],
  delete_maintenance_window_for_endpoint: ['DeleteMaintenanceWindowForEndpointById'],
  get_maintenance_window_for_logical_group: ['GetMaintenanceWindowForLogicalGroupById'],
  create_maintenance_window_for_logical_group: ['CreateMaintenanceWindowForLogicalGroupById'],
  update_maintenance_window_for_logical_group: ['UpdateMaintenanceWindowForLogicalGroupById'],
  delete_maintenance_window_for_logical_group: ['DeleteMaintenanceWindowForLogicalGroupById'],
  list_industrial_endpoints: ['GetIndustrialEndpoints'],
  get_industrial_endpoint: ['GetIndustrialEndpoint'],
  create_industrial_endpoint: ['CreateIndustrialEndpoint'],
  update_industrial_endpoint: ['UpdateIndustrialEndpoint'],
  delete_industrial_endpoint: ['DeleteIndustrialEndpoint'],
  list_network_endpoints: ['GetNetworkEndpoints'],
  get_network_endpoint: ['GetNetworkEndpoint'],
  create_network_endpoint: ['CreateNetworkEndpoint'],
  update_network_endpoint: ['UpdateNetworkEndpoint'],
  delete_network_endpoint: ['DeleteNetworkEndpoint'],
  delete_endpoint: ['DeleteEndpoint'],
  list_unmanaged_endpoints: ['GetAllUnmanagedEndpoints'],
  get_unmanaged_endpoint: ['GetUnmanagedEndpoint'],
  delete_unmanaged_endpoint: ['DeleteUnmanagedEndpoint'],
  get_entra_id_data: ['GetEntraIdEndpointDataByDeviceId'],
  link_entra_id_data: ['SetEntraIdEndpointData'],
  unlink_entra_id_data: ['DeleteEntraIdEndpointData'],
};
