/**
 * The bConnect API operation each tool of this server calls, by operationId in
 * the `endpoints` OpenAPI spec (openapi-specs/<release>/). One line per tool; add
 * one when you add a tool.
 *
 * The spec-conformance guard (__tests__/spec-conformance.guard.test.ts) checks
 * every tool against its entry for both bMS releases: the operation must exist,
 * and the tool's request must go to that operation's method and route.
 *
 * A tool that differs only by endpoint type is one tool with a `type` argument
 * (REQ-SRV-029, #174): one line per route, `'tool[type=WindowsEndpoint]'`, and
 * `'tool[type=]'` for the call without a type. The values are the API's
 * EndpointType names; which ones a release offers comes from the specs.
 */
export const TOOL_OPERATIONS: Readonly<Record<string, readonly string[]>> = {
  'list_endpoints[type=]': ['GetEndpoints'],
  'list_endpoints[type=WindowsEndpoint]': ['GetWindowsEndpoints'],
  'list_endpoints[type=MacEndpoint]': ['GetMacEndpoints'],
  'list_endpoints[type=AndroidEndpoint]': ['GetAndroidEndpoints'],
  'list_endpoints[type=IOSEndpoint]': ['GetIOSEndpoints'],
  'list_endpoints[type=LinuxEndpoint]': ['GetLinuxEndpoints'],
  'list_endpoints[type=NetworkEndpoint]': ['GetNetworkEndpoints'],
  'list_endpoints[type=IndustrialEndpoint]': ['GetIndustrialEndpoints'],
  'get_endpoint[type=]': ['GetEndpoint'],
  'get_endpoint[type=WindowsEndpoint]': ['GetWindowsEndpoint'],
  'get_endpoint[type=MacEndpoint]': ['GetMacEndpoint'],
  'get_endpoint[type=AndroidEndpoint]': ['GetAndroidEndpoint'],
  'get_endpoint[type=IOSEndpoint]': ['GetIOSEndpoint'],
  'get_endpoint[type=LinuxEndpoint]': ['GetLinuxEndpoint'],
  'get_endpoint[type=NetworkEndpoint]': ['GetNetworkEndpoint'],
  'get_endpoint[type=IndustrialEndpoint]': ['GetIndustrialEndpoint'],
  'delete_endpoint[type=]': ['DeleteEndpoint'],
  'delete_endpoint[type=WindowsEndpoint]': ['DeleteWindowsEndpoint'],
  'delete_endpoint[type=MacEndpoint]': ['DeleteMacEndpoint'],
  'delete_endpoint[type=AndroidEndpoint]': ['DeleteAndroidEndpoint'],
  'delete_endpoint[type=IOSEndpoint]': ['DeleteIOSEndpoint'],
  'delete_endpoint[type=LinuxEndpoint]': ['DeleteLinuxEndpoint'],
  'delete_endpoint[type=NetworkEndpoint]': ['DeleteNetworkEndpoint'],
  'delete_endpoint[type=IndustrialEndpoint]': ['DeleteIndustrialEndpoint'],
  'update_endpoint[type=WindowsEndpoint]': ['UpdateWindowsEndpoint'],
  'update_endpoint[type=MacEndpoint]': ['UpdateMacEndpoint'],
  'update_endpoint[type=AndroidEndpoint]': ['UpdateAndroidEndpoint'],
  'update_endpoint[type=IOSEndpoint]': ['UpdateIOSEndpoint'],
  'update_endpoint[type=LinuxEndpoint]': ['UpdateLinuxEndpoint'],
  'update_endpoint[type=NetworkEndpoint]': ['UpdateNetworkEndpoint'],
  'update_endpoint[type=IndustrialEndpoint]': ['UpdateIndustrialEndpoint'],
  'start_enrollment[type=WindowsEndpoint]': ['StartWindowsEndpointEnrollment'],
  'start_enrollment[type=MacEndpoint]': ['StartMacEndpointEnrollment'],
  'start_enrollment[type=AndroidEndpoint]': ['StartAndroidEndpointEnrollment'],
  'start_enrollment[type=IOSEndpoint]': ['StartIosEndpointEnrollment'],
  'list_endpoints_by_logical_group[type=]': ['GetEndpointsByLogicalGroupId'],
  'list_endpoints_by_logical_group[type=WindowsEndpoint]': ['GetWindowsEndpointsByLogicalGroupId'],
  list_logical_groups: ['GetLogicalGroups'],
  get_logical_group: ['GetLogicalGroup'],
  create_android_endpoint: ['CreateAndroidEndpoint'],
  create_ios_endpoint: ['CreateIOSEndpoint'],
  create_windows_endpoint: ['CreateWindowsEndpoint'],
  trigger_intune_installation: ['TriggerInstallationViaIntune'],
  create_linux_endpoint: ['CreateLinuxEndpoint'],
  create_mac_endpoint: ['CreateMacEndpoint'],
  create_logical_group: ['CreateLogicalGroup'],
  update_logical_group: ['UpdateLogicalGroup'],
  delete_logical_group: ['DeleteLogicalGroup'],
  get_maintenance_window_for_endpoint: ['GetMaintenanceWindowForEndpointById'],
  create_maintenance_window_for_endpoint: ['CreateMaintenanceWindowForEndpointById'],
  update_maintenance_window_for_endpoint: ['UpdateMaintenanceWindowForEndpointById'],
  delete_maintenance_window_for_endpoint: ['DeleteMaintenanceWindowForEndpointById'],
  get_maintenance_window_for_logical_group: ['GetMaintenanceWindowForLogicalGroupById'],
  create_maintenance_window_for_logical_group: ['CreateMaintenanceWindowForLogicalGroupById'],
  update_maintenance_window_for_logical_group: ['UpdateMaintenanceWindowForLogicalGroupById'],
  delete_maintenance_window_for_logical_group: ['DeleteMaintenanceWindowForLogicalGroupById'],
  create_industrial_endpoint: ['CreateIndustrialEndpoint'],
  create_network_endpoint: ['CreateNetworkEndpoint'],
  list_unmanaged_endpoints: ['GetAllUnmanagedEndpoints'],
  get_unmanaged_endpoint: ['GetUnmanagedEndpoint'],
  delete_unmanaged_endpoint: ['DeleteUnmanagedEndpoint'],
  get_entra_id_data: ['GetEntraIdEndpointDataByDeviceId'],
  link_entra_id_data: ['SetEntraIdEndpointData'],
  unlink_entra_id_data: ['DeleteEntraIdEndpointData'],
};
