/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_endpoints: ["GET"],
  get_endpoint: ["GET"],
  delete_endpoint: ["DELETE"],
  update_endpoint: ["PATCH"],
  start_enrollment: ["POST"],
  list_endpoints_by_logical_group: ["GET"],
  list_logical_groups: ["GET"],
  get_logical_group: ["GET"],
  create_android_endpoint: ["POST"],
  create_ios_endpoint: ["POST"],
  create_windows_endpoint: ["POST"],
  trigger_intune_installation: ["POST"],
  create_linux_endpoint: ["POST"],
  create_mac_endpoint: ["POST"],
  create_logical_group: ["POST"],
  update_logical_group: ["PATCH"],
  delete_logical_group: ["DELETE"],
  get_maintenance_window_for_endpoint: ["GET"],
  create_maintenance_window_for_endpoint: ["POST"],
  update_maintenance_window_for_endpoint: ["PATCH", "PUT"],
  delete_maintenance_window_for_endpoint: ["DELETE"],
  get_maintenance_window_for_logical_group: ["GET"],
  create_maintenance_window_for_logical_group: ["POST"],
  update_maintenance_window_for_logical_group: ["PATCH", "PUT"],
  delete_maintenance_window_for_logical_group: ["DELETE"],
  create_industrial_endpoint: ["POST"],
  create_network_endpoint: ["POST"],
  list_unmanaged_endpoints: ["GET"],
  get_unmanaged_endpoint: ["GET"],
  delete_unmanaged_endpoint: ["DELETE"],
  get_entra_id_data: ["GET"],
  link_entra_id_data: ["POST"],
  unlink_entra_id_data: ["DELETE"],
};
