/**
 * GENERATED by scripts/generate-query-parameters.mjs from src/operations.ts —
 * do not edit. Regenerate after an operations.ts change;
 * __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per merged tool (REQ-SRV-029, #174): its routes (variants) and the selector
 * values that choose each; null means the argument is left out.
 */
import type { ToolVariantTable } from "@bconnect/mcp-core";

export const TOOL_VARIANTS: ToolVariantTable = {
  list_endpoints: {
    "list_endpoints[type=]": {"type": null},
    "list_endpoints[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
    "list_endpoints[type=MacEndpoint]": {"type": "MacEndpoint"},
    "list_endpoints[type=AndroidEndpoint]": {"type": "AndroidEndpoint"},
    "list_endpoints[type=IOSEndpoint]": {"type": "IOSEndpoint"},
    "list_endpoints[type=LinuxEndpoint]": {"type": "LinuxEndpoint"},
    "list_endpoints[type=NetworkEndpoint]": {"type": "NetworkEndpoint"},
    "list_endpoints[type=IndustrialEndpoint]": {"type": "IndustrialEndpoint"},
  },
  get_endpoint: {
    "get_endpoint[type=]": {"type": null},
    "get_endpoint[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
    "get_endpoint[type=MacEndpoint]": {"type": "MacEndpoint"},
    "get_endpoint[type=AndroidEndpoint]": {"type": "AndroidEndpoint"},
    "get_endpoint[type=IOSEndpoint]": {"type": "IOSEndpoint"},
    "get_endpoint[type=LinuxEndpoint]": {"type": "LinuxEndpoint"},
    "get_endpoint[type=NetworkEndpoint]": {"type": "NetworkEndpoint"},
    "get_endpoint[type=IndustrialEndpoint]": {"type": "IndustrialEndpoint"},
  },
  delete_endpoint: {
    "delete_endpoint[type=]": {"type": null},
    "delete_endpoint[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
    "delete_endpoint[type=MacEndpoint]": {"type": "MacEndpoint"},
    "delete_endpoint[type=AndroidEndpoint]": {"type": "AndroidEndpoint"},
    "delete_endpoint[type=IOSEndpoint]": {"type": "IOSEndpoint"},
    "delete_endpoint[type=LinuxEndpoint]": {"type": "LinuxEndpoint"},
    "delete_endpoint[type=NetworkEndpoint]": {"type": "NetworkEndpoint"},
    "delete_endpoint[type=IndustrialEndpoint]": {"type": "IndustrialEndpoint"},
  },
  update_endpoint: {
    "update_endpoint[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
    "update_endpoint[type=MacEndpoint]": {"type": "MacEndpoint"},
    "update_endpoint[type=AndroidEndpoint]": {"type": "AndroidEndpoint"},
    "update_endpoint[type=IOSEndpoint]": {"type": "IOSEndpoint"},
    "update_endpoint[type=LinuxEndpoint]": {"type": "LinuxEndpoint"},
    "update_endpoint[type=NetworkEndpoint]": {"type": "NetworkEndpoint"},
    "update_endpoint[type=IndustrialEndpoint]": {"type": "IndustrialEndpoint"},
  },
  start_enrollment: {
    "start_enrollment[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
    "start_enrollment[type=MacEndpoint]": {"type": "MacEndpoint"},
    "start_enrollment[type=AndroidEndpoint]": {"type": "AndroidEndpoint"},
    "start_enrollment[type=IOSEndpoint]": {"type": "IOSEndpoint"},
  },
  list_endpoints_by_logical_group: {
    "list_endpoints_by_logical_group[type=]": {"type": null},
    "list_endpoints_by_logical_group[type=WindowsEndpoint]": {"type": "WindowsEndpoint"},
  },
};
