/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per bMS release and tool: the query parameters of the tool's GET operation,
 * as the properties the tool offers (#179). Tools send exactly these.
 */
import { type QueryParameterTable, INCLUDE_SUBFOLDERS_PROPERTY, PAGE_PROPERTY, PAGE_SIZE_PROPERTY } from "@bconnect/mcp-core";

export const QUERY_PARAMETERS: QueryParameterTable = {
  "25R2": {
    list_installed_windows_software: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_endpoint: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_logical_group: {
      includeSubfolders: INCLUDE_SUBFOLDERS_PROPERTY,
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_dynamic_group: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
  },
  "26R1": {
    list_installed_windows_software: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_endpoint: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_logical_group: {
      includeSubfolders: INCLUDE_SUBFOLDERS_PROPERTY,
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_installed_software_by_dynamic_group: {
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable value is Vendor, Name, Category."},
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Vendor, Name, Category (e.g. Name asc)."},
      Category: {"type":"string","description":"Filters results by exactly matching category."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_software_bundles: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are Name"},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name, Comment, ParentName."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_bundle_applications: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are BundleName, ApplicationName, ApplicationVendor, Order."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are BundleName, ApplicationId, ApplicationName, ApplicationVendor."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_bundle_applications_by_bundle: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible values are BundleName, ApplicationName, ApplicationVendor, Order."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are BundleName, ApplicationId, ApplicationName, ApplicationVendor."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_bundle_folders: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
    },
    list_bundle_folders_by_folder: {
      OrderBy: {"type":"string","description":"Sorts results by property name and with sort direction. Multiple properties are separated by comma. Possible value is Name."},
      SearchQuery: {"type":"string","description":"Filters results by matching the given value against searchable properties. Searchable values are Name and Comment."},
      Name: {"type":"string","description":"Filters result by matching the exact value against Name."},
      Page: PAGE_PROPERTY,
      PageSize: PAGE_SIZE_PROPERTY,
      includeSubfolders: {"type":"boolean","description":"If true, items in sub-folders are also returned (default false)."},
    },
  },
};
