/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_installed_windows_software: ["25R2", "26R1"],
  list_installed_software_by_endpoint: ["25R2", "26R1"],
  list_installed_software_by_logical_group: ["25R2", "26R1"],
  list_installed_software_by_dynamic_group: ["25R2", "26R1"],
  list_software_bundles: ["26R1"],
  get_software_bundle: ["26R1"],
  create_software_bundle: ["26R1"],
  delete_software_bundle: ["26R1"],
  list_bundle_applications: ["26R1"],
  list_bundle_applications_by_bundle: ["26R1"],
  add_application_to_bundle: ["26R1"],
  delete_bundle_application: ["26R1"],
  replace_application_in_bundle: ["26R1"],
  list_bundle_folders: ["26R1"],
  get_bundle_folder: ["26R1"],
  list_bundle_folders_by_folder: ["26R1"],
  create_bundle_folder: ["26R1"],
  delete_bundle_folder: ["26R1"],
  update_bundle_folder: ["26R1"],
};
