/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_installed_windows_software: ["GET"],
  list_installed_software_by_endpoint: ["GET"],
  list_installed_software_by_logical_group: ["GET"],
  list_installed_software_by_dynamic_group: ["GET"],
  list_software_bundles: ["GET"],
  get_software_bundle: ["GET"],
  create_software_bundle: ["POST"],
  delete_software_bundle: ["DELETE"],
  list_bundle_applications: ["GET"],
  list_bundle_applications_by_bundle: ["GET"],
  add_application_to_bundle: ["POST"],
  delete_bundle_application: ["DELETE"],
  replace_application_in_bundle: ["PATCH"],
  list_bundle_folders: ["GET"],
  get_bundle_folder: ["GET"],
  list_bundle_folders_by_folder: ["GET"],
  create_bundle_folder: ["POST"],
  delete_bundle_folder: ["DELETE"],
  update_bundle_folder: ["PATCH"],
};
