/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the HTTP methods of the operations it calls, in either bMS release.
 * The tool's MCP annotations (read-only, destructive) are derived from these
 * (REQ-SRV-024).
 */
import type { ToolMethodTable } from "@bconnect/mcp-core";

export const TOOL_METHODS: ToolMethodTable = {
  list_ad_groups: ["GET"],
  get_ad_group: ["GET"],
  list_ad_subgroups: ["GET"],
  list_ad_groups_by_org_unit: ["GET"],
  list_ad_objects: ["GET"],
  get_ad_object: ["GET"],
  list_ad_object_memberships: ["GET"],
  list_ad_objects_by_group: ["GET"],
  list_ad_objects_by_org_unit: ["GET"],
  list_ad_users: ["GET"],
  get_ad_user: ["GET"],
  list_ad_users_by_group: ["GET"],
  list_ad_users_by_org_unit: ["GET"],
  list_org_units: ["GET"],
  get_org_unit: ["GET"],
  list_org_units_by_org_unit: ["GET"],
};
