/**
 * GENERATED by scripts/generate-query-parameters.mjs from openapi-specs/ and
 * src/operations.ts — do not edit. Regenerate after a spec or operations.ts
 * change; __tests__/query-params.guard.test.ts fails when this table drifts.
 *
 * Per tool: the bMS releases in which each of its operations exists with the
 * route the tool calls. The selected release lists only these tools and
 * refuses the others by name (REQ-SRV-028, #159).
 */
import type { ToolReleaseTable } from "@bconnect/mcp-core";

export const TOOL_RELEASES: ToolReleaseTable = {
  list_ad_groups: ["25R2", "26R1"],
  get_ad_group: ["25R2", "26R1"],
  list_ad_subgroups: ["25R2", "26R1"],
  list_ad_groups_by_org_unit: ["25R2", "26R1"],
  list_ad_objects: ["25R2", "26R1"],
  get_ad_object: ["25R2", "26R1"],
  list_ad_object_memberships: ["25R2", "26R1"],
  list_ad_objects_by_group: ["25R2", "26R1"],
  list_ad_objects_by_org_unit: ["25R2", "26R1"],
  list_ad_users: ["25R2", "26R1"],
  get_ad_user: ["25R2", "26R1"],
  list_ad_users_by_group: ["25R2", "26R1"],
  list_ad_users_by_org_unit: ["25R2", "26R1"],
  list_org_units: ["25R2", "26R1"],
  get_org_unit: ["25R2", "26R1"],
  list_org_units_by_org_unit: ["25R2", "26R1"],
};
