/**
 * Generated query-parameter tables (#179, REQ-QA-001 AC 3).
 *
 * Each server's `src/query-params.ts` is generated by
 * scripts/generate-query-parameters.mjs from the bundled specs and the
 * server's `src/operations.ts`, and committed (the specs aren't shipped). This
 * guard fails when a table is missing, edited by hand, or out of date, and checks
 * on its own that every table lists, per release, exactly the query parameters
 * of the tool's GET operation, with the spec's type and enum values.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';
import { RELEASES, loadOperations, type Schema } from './lib/spec.js';
import { ROOT, SERVERS } from './lib/exerciser.js';

const REGENERATE = 'run `node scripts/generate-query-parameters.mjs` and commit the src/query-params.ts files';

it('every table is up to date with the specs', () => {
  expect(existsSync(join(ROOT, 'scripts', 'generate-query-parameters.mjs')), 'generator missing').toBe(true);
  const out = execFileSync(process.execPath, [join(ROOT, 'scripts', 'generate-query-parameters.mjs'), '--check'], { cwd: ROOT, encoding: 'utf8' });
  expect(out, REGENERATE).toMatch(/up to date/);
});

const deref = (spec: Schema, s: Schema | undefined): Schema => {
  let x = s ?? {};
  if (Array.isArray(x.allOf) && x.allOf.length === 1) {x = x.allOf[0];}
  while (x && x.$ref) {x = x.$ref.replace(/^#\//, '').split('/').reduce((n: Schema, k: string) => n[k], spec);}
  return x;
};

describe.each(SERVERS)('%s', (server) => {
  it('lists, per release, exactly the query parameters of each tool\'s GET operation, typed as the spec says', async () => {
    const file = join(ROOT, server, 'src', 'query-params.ts');
    expect(existsSync(file), `${file} missing; ${REGENERATE}`).toBe(true);
    expect(readFileSync(file, 'utf8')).toMatch(/GENERATED by scripts\/generate-query-parameters\.mjs/);
    const { QUERY_PARAMETERS } = await import(pathToFileURL(file).href);
    const { TOOL_OPERATIONS } = await import(pathToFileURL(join(ROOT, server, 'src', 'operations.ts')).href);
    const wrong: string[] = [];
    for (const release of RELEASES) {
      const ops = loadOperations(release);
      const table: Record<string, Record<string, Schema>> = QUERY_PARAMETERS[release] ?? {};
      for (const [tool, ids] of Object.entries<string[]>(TOOL_OPERATIONS)) {
        // An operationId can exist in several specs (GetFolders): the server's own domain, or any
        // domain for a server without its own spec (groups uses endpoints).
        const all = ops.filter((o) => ids.includes(o.operationId) && o.method === 'GET');
        const own = all.filter((o) => o.domain === server.replace(/^bconnect-|-mcp$/g, ''));
        const gets = own.length ? own : all;
        const params = new Map<string, Schema>();
        for (const o of gets) {
          for (const p of o.spec.paths[o.path].get.parameters ?? []) {
            if (p.in === 'query' && !params.has(p.name)) {params.set(p.name, deref(o.spec, p.schema));}
          }
        }
        const listed = table[tool];
        if (params.size === 0) {
          if (listed) {wrong.push(`${release} ${tool}: listed, but its operation has no query parameters`);}
          continue;
        }
        if (!listed) { wrong.push(`${release} ${tool}: missing`); continue; }
        if (Object.keys(listed).join() !== [...params.keys()].join()) {wrong.push(`${release} ${tool}: ${Object.keys(listed).join()} ≠ ${[...params.keys()].join()}`);}
        for (const [name, schema] of params) {
          const prop = listed[name];
          if (!prop) {continue;}
          const type = schema.enum ? 'string' : schema.type === 'number' ? 'integer' : schema.type;
          if (prop.type !== type) {wrong.push(`${release} ${tool} ${name}: type ${prop.type} ≠ ${type}`);}
          if (schema.enum && JSON.stringify(prop.enum) !== JSON.stringify(schema.enum)) {wrong.push(`${release} ${tool} ${name}: enum differs`);}
          if (typeof prop.description !== 'string' || prop.description.length < 5) {wrong.push(`${release} ${tool} ${name}: no description`);}
        }
      }
      for (const tool of Object.keys(table)) {
        if (!TOOL_OPERATIONS[tool]) {wrong.push(`${release} ${tool}: not in operations.ts`);}
      }
    }
    expect(wrong).toEqual([]);
  });
});
